// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAffvT2QEIdu_Hi8fzkpPM_ZH6RNeiEOh4',
    appId: '1:286092960310:web:9f470855b97d7da2082e97',
    messagingSenderId: '286092960310',
    projectId: 'notification-supabase',
    authDomain: 'notification-supabase.firebaseapp.com',
    storageBucket: 'notification-supabase.appspot.com',
    measurementId: 'G-67CW2X1DYF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEMy73H6DFYJqReq7vQt8pEYeT6YN_WmQ',
    appId: '1:286092960310:android:8771aa721e137502082e97',
    messagingSenderId: '286092960310',
    projectId: 'notification-supabase',
    storageBucket: 'notification-supabase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxhRIOycdSllrSU4KlEB3i_o-g7VKIU18',
    appId: '1:286092960310:ios:721a1ff70b59220e082e97',
    messagingSenderId: '286092960310',
    projectId: 'notification-supabase',
    storageBucket: 'notification-supabase.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxhRIOycdSllrSU4KlEB3i_o-g7VKIU18',
    appId: '1:286092960310:ios:721a1ff70b59220e082e97',
    messagingSenderId: '286092960310',
    projectId: 'notification-supabase',
    storageBucket: 'notification-supabase.appspot.com',
    iosBundleId: 'com.example.test',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAffvT2QEIdu_Hi8fzkpPM_ZH6RNeiEOh4',
    appId: '1:286092960310:web:fd69f02b02f9220b082e97',
    messagingSenderId: '286092960310',
    projectId: 'notification-supabase',
    authDomain: 'notification-supabase.firebaseapp.com',
    storageBucket: 'notification-supabase.appspot.com',
    measurementId: 'G-BZXJ22B92L',
  );
}
